import type { Metadata } from "next";
import { Unbounded as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["cyrillic"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={fontSans.className}>{children}</body>
    </html>
  );
}
