import type { Metadata } from "next";
import { Unbounded as FontSans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Script from "next/script";

const fontSans = FontSans({
  subsets: ["cyrillic"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <Script
          src="https://vk.com/js/api/openapi.js?169"
          type="text/javascript"
          strategy="beforeInteractive"
        ></Script>
      </head>
      <body className={fontSans.className}>
        {children}
        <Toaster />
        <Script id="vk-init" type="text/javascript">
          {`
            VK.init({
              apiId: 51790924
            });
          `}
        </Script>
      </body>
    </html>
  );
}
